inherit_from: .rubocop_todo.yml

# Keep diffs clean
Layout/TrailingBlankLines:
  EnforcedStyle: final_blank_line

# Allow the gem to have a non-snakecase name
Naming/FileName:
  Exclude:
    - 'lib/onfleet-ruby.rb'

Style/Documentation:
  Enabled: false

